### ISSUE TITLE
ss58Encode does not handle the "null" address

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/oo7#51]
Not sure if this is intentional or not, but when passing the "null" address to ss58Encode, it barfs:
```
> x1
AccountId(32) [209, 114, 167, 76, 218, 76, 134, 89, 18, 195, 43, 160, 168, 10, 87, 174, 105, 171, 174, 65, 14, 92, 203, 89, 222, 232, 78, 47, 68, 50, 219, 79]

> ss58Encode(x1)
"5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ"

> x2
AccountId []

> ss58Encode(x2)
ss58.js:39 Uncaught Error: Unknown item to encode as ss58. Passing back.
    at ss58Encode (ss58.js:39)
    at <anonymous>:1:1
```

This error came up when trying to use the Bonds UI to return a storage element of type `AccountID` `before the value was set.

**Comment by gavofyork** [comment]
that's not the null address: that's just an invalid address (`AccountId` doesn't check that you give it something sensible in its constructor - it's just a simple type wrapper over a `Uint8Array`).

**Comment by shawntabrizi** [comment]
Sorry for the delayed response here. Imagine this scenario:

We have a custom runtime which has a storage mapping from key to AccountId:

```
decl_storage! {
	trait Store for Module<T: Trait> as RuntimeExampleStorage {
		Value: map u32 => T::AccountId;
	}
}
```

We then integrate a basic UI using the Bonds framework to allow users to look at the storage for different keys:
