### ISSUE TITLE
ss58Decode fails with the Alice account of the tutorial

### ISSUE THREAD

**Issue by attente** [paritytech/oo7#72]
Testing out the tutorial for creating a custom substrate chain, at the step to set the payment, the call to `runtime.balances.ss58Decode('F7Gh')` fails with this error (because `ss58Decode` returns `null`):

`Value cannot be encoded as type: null, AccountId`

The workaround is to use Alice's address directly: `5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ`, thanks Shawn Tabrizi!

**Comment by gavofyork** [comment]
The tutorial is out of date; it should be `runtime.indices.ss58Decode('F7Gh')`. CC @shawntabrizi
