### ISSUE TITLE
Error when submitting runtime upgrade

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/oo7#92]
There seems to be an error related to:
https://github.com/paritytech/oo7/commit/f17e30953590df4ce47830afdf65fd0640d9b0d5

Where substrate rejects the message with the following errors:

```
Failed subscription: {code: -32603, message: "Unknown error occured", data: "Error(Pool(InvalidTransaction(-127)), State { next…cktrace: InternalBacktrace { backtrace: None } })"}
```

Confirmed that it works in the Polkadot UI where Jaco seemed to have made the equivalent changes here:

https://github.com/polkadot-js/apps/commit/1e86fb745c5ff1484dccd5070fa377618afa6207

https://github.com/polkadot-js/api/commit/c1a6f0230c79787c9bf9e0d985878d7ec4b306ae

**Comment by gavofyork** [comment]
Should work now.
